###################################
# Site-wide configuration
####################################

title: Gabriel Walker | Data Science
email: gabrielbwalker@gmail.com
description: Gabe Walker's personal website.
url: https://gbwalker.github.io
keywords: ["Gabe", "Walker", "github"]

###################################
# Jekyll configuration
####################################

timezone:          New York
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

###################################
# Site Owner configuration
####################################

owner:
  name: Gabriel Walker
  avatar: icon.png
  job: "Data Science"
  bio: "A selection of projects."
  email: "gabrielbwalker@gmail.com"
  disqus-shortname: #username
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: gbwalker
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: gbwalker
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username